### ISSUE TITLE
Установка Raspicam

### ISSUE THREAD

**Issue by copterspace** [gaidel/img-spectru#3]
После установки pip3 install picamera модуль picamera не работает, выдаёт ошибку:
```
pi@HSPR-0851:~/test_ws/src/hspr_test $ python3 -c "import picamera"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/__init__.py", line 72, in <module>
    from picamera.exc import (
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/exc.py", line 41, in <module>
    import picamera.mmal as mmal
  File "/home/pi/.local/lib/python3.7/site-packages/picamera/mmal.py", line 49, in <module>
    _lib = ct.CDLL('libmmal.so')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmmal.so: cannot open shared object file: No such file or directory
```

нагуглил вот:
https://stackoverflow.com/questions/27777547/missing-libmmal-so-with-picamera-library
https://stackoverflow.com/questions/29616749/can-i-use-picamera-with-this-version-of-ubuntu-on-a-raspberry-pi-2-model-b/32947446#32947446

думаю такой "с фига ли, у меня ж Raspbian?"

однако:
```
pi@HSPR-0851:~/test_ws/src/hspr_test $ uname -a
Linux HSPR-0851 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
```
а никакой не Raspbian

последовал `sudo rpi-update` и ребут... после которого RPI подохла напрочь и окирпичилась...
залил на флэху обратно собранный образ. Она, слава Богу, раскирпичилась.
Буду искать другие пути...

**Comment by copterspace** [comment]
`sudo apt-get install libraspberrypi-bin libraspberrypi-dev` - не помогло, та же ошибка
а сама распикамера работает ОК на `Linux clever-4727 5.4.59-v7+ #1338 SMP Fri Aug 28 11:49:42 BST 2020 armv7l GNU/Linux` с другой флэхи

@urpylka , не поможешь ли, чем лечить?...

**Comment by copterspace** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?p=1729089#p1729089
<br>**MMAL, and hence raspistill and raspivid, currently have unresolved issues in a 64bit userland. For these reasons it is currently disabled.**
<br>долбаный насос... так хорошо всё начиналось... обратно на armhf теперь ?...

**Comment by copterspace** [comment]
Ждём решения проблемы вот тут: https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/10
